name: 'Setup Yarn dependencies'
description: 'Setup Node.js, enable Corepack, cache Yarn dependencies, and install packages'

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        
    - name: Enable Corepack
      shell: bash
      run: corepack enable

    - name: Cache Yarn dependencies
      uses: actions/cache@v4
      with:
        path: |
          .yarn/cache
          .yarn/unplugged
          .yarn/install-state.gz
          node_modules
        key: yarn-${{ runner.os }}-${{ hashFiles('yarn.lock') }}
        restore-keys: |
          yarn-${{ runner.os }}-

    - name: Install dependencies
      shell: bash
      run: yarn install --immutable

