compressionLevel: mixed

enableGlobalCache: false

httpTimeout: 60000

npmAuditExcludePackages:
  - pdfjs-dist

logFilters:
  - code: YN0002
    level: discard
  - code: YN0060
    level: discard
  - code: YN0086
    level: discard

nodeLinker: node-modules
