compressionLevel: mixed

enableGlobalCache: false

npmAuditExcludePackages:
# This package isnt used directly in the code but remains as a dependency of @atlaskit/media-viewer package for internal support reasons
# TODO: Remove this once @atlaskit/media-viewer is updated to a version that doesn't depend on this package
# See https://asecurityteam.atlassian.net/browse/PBAC-2014

  - pdfjs-dist

nodeLinker: node-modules
