networks:
  e2e:

services: 
  wiremock-mockedteams:
    image: wiremock/wiremock
    command: >
      --https-port 443
      --verbose
      --https-keystore /home/wiremock_ssl_certs/wiremock-mockedteams.p12
    volumes:
      - ./wiremock-endpoint/mappings:/home/wiremock/mappings
      - ./certs:/home/wiremock_ssl_certs
    networks:
      e2e:
        aliases:
          - mockedteams.atlassian.net
    expose:
      - 443

  atlascode-e2e:
    image: atlascode-e2e
    platform: linux/amd64
    volumes:
      - ${PWD}/../..:/atlascode
    environment:
      # - ATLASCODE_TEST_USER_API_TOKEN=${ATLASCODE_TEST_USER_API_TOKEN}
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    depends_on:
      - wiremock-mockedteams
    networks:
      - e2e
    ports:
      - "9988:9988"
